/**
 * WhatsApp & Email Automation Helper
 * Integrates with app.messageautosender.com API & WhatsApp Direct Web link
 */

export interface WhatsAppConfig {
  username?: string;
  password?: string;
  senderNo?: string;
  enabled?: boolean;
}

export const DEFAULT_WHATSAPP_TEMPLATES = {
  payslip: `Dear {NAME}, your Payslip for {MONTH} is generated by {COMPANY_NAME}.
Basic Pay: ₹{BASIC}
Net Salary: ₹{NET_SALARY}
Status: {STATUS}
Pay Date: {PAY_DATE}
Please check your HR Employee Portal for the full breakdown.`,

  missPunch: `Attention {NAME}, a Miss Punch was logged on {DATE} for your record at {COMPANY_NAME}.
Please log into your HR Portal to submit a Miss Punch Regularization request.
HR Desk Contact: {HR_CONTACT}`,

  leaveStatus: `Hello {NAME}, your Leave Request for {DATES} ({LEAVE_TYPE}) has been {STATUS} at {COMPANY_NAME}.
Approved/Processed By: {BY}
Remarks: {REMARKS}`,

  lateWarning: `Notice for {NAME}: You arrived late on {DATE} (Check-in: {CHECK_IN}).
Please adhere to company shift timings ({SHIFT_TIMINGS}).
Late Count this month: {LATE_COUNT} day(s).`,

  salaryDisbursed: `Great News {NAME}! Your salary of ₹{NET_SALARY} for {MONTH} has been credited via {PAYMENT_METHOD}.
Thank you for your hard work at {COMPANY_NAME}!`,

  customNotice: `Important Notice from {COMPANY_NAME} HR:
{NOTICE_BODY}
Date: {DATE}`
};

export const DEFAULT_EMAIL_TEMPLATES = {
  payslipSubject: `Payslip Issued for {MONTH} - {COMPANY_NAME}`,
  payslipBody: `Dear {NAME},

Your monthly salary payslip for {MONTH} has been generated.

Summary:
- Basic Salary: ₹{BASIC}
- Allowances: ₹{ALLOWANCES}
- Total Deductions: ₹{DEDUCTIONS}
- Net Payable: ₹{NET_SALARY}
- Payment Status: {STATUS}

You can view and download your full PDF payslip by logging into the Rathi Buildmart HR Portal.

Best regards,
HR & Payroll Management
{COMPANY_NAME}`,

  missPunchSubject: `Attendance Action Required: Miss Punch Alert for {DATE}`,
  missPunchBody: `Dear {NAME},

Our automated attendance tracker registered a Missed Punch for your account on {DATE}.

Please log into your employee portal immediately to review and submit an approval request.

HR Support Contact: {HR_CONTACT}

Thank you,
{COMPANY_NAME} HR Team`,

  leaveSubject: `Leave Request Update - {STATUS}`,
  leaveBody: `Dear {NAME},

Your leave application for {DATES} ({LEAVE_TYPE}) has been {STATUS}.

Details:
- Applied On: {APPLIED_ON}
- Status: {STATUS}
- Processed By: {BY}
- Remarks: {REMARKS}

Regards,
{COMPANY_NAME}`
};

/**
 * Replace placeholders like {NAME}, {NET_SALARY}, {COMPANY_NAME} in templates
 */
export function processTemplate(template: string, variables: Record<string, string | number | undefined>): string {
  let result = template || '';
  Object.keys(variables).forEach((key) => {
    const val = variables[key] !== undefined && variables[key] !== null ? String(variables[key]) : '';
    const regex = new RegExp(`\\{${key}\\}`, 'g');
    result = result.replace(regex, val);
  });
  return result;
}

/**
 * Format phone number to clean digit format with country code (e.g. 919876543210)
 */
export function formatPhoneNumber(phone: string | undefined): string {
  if (!phone) return '';
  let digits = phone.replace(/\D/g, '');
  // If 10 digits without country code, assume India +91
  if (digits.length === 10) {
    digits = '91' + digits;
  }
  return digits;
}

/**
 * Construct the messageautosender.com direct API endpoint URL
 */
export function buildMessageAutoSenderUrl(
  username: string,
  password: string,
  receiverMobileNo: string,
  receiverName: string,
  message: string
): string {
  const cleanMobile = formatPhoneNumber(receiverMobileNo);
  const encodedUser = encodeURIComponent(username || '');
  const encodedPass = encodeURIComponent(password || '');
  const encodedMobile = encodeURIComponent(cleanMobile || receiverMobileNo || '');
  const encodedName = encodeURIComponent(receiverName || 'Employee');
  const encodedMessage = encodeURIComponent(message || '');

  return `https://app.messageautosender.com/message/new?username=${encodedUser}&password=${encodedPass}&receiverMobileNo=${encodedMobile}&receiverName=${encodedName}&message=${encodedMessage}`;
}

/**
 * Construct the Excel / Google Sheet formula matching user request:
 * =HYPERLINK("https://app.messageautosender.com/message/new?username="&User&"&password="&Password&"&receiverMobileNo="&B6&"&receiverName=test&message=MESSAGETEST","Manual Test Send")
 */
export function buildMessageAutoSenderExcelFormula(
  userRefOrVal: string,
  passRefOrVal: string,
  mobileCellRef: string,
  nameCellRef: string,
  messageCellRefOrText: string,
  label: string = 'Send WhatsApp'
): string {
  // If provided as raw string instead of cell ref (e.g. "admin"), wrap in quotes in formula if needed
  const userExpr = userRefOrVal.startsWith('"') || userRefOrVal.match(/^[A-Z]+\d+$/) ? userRefOrVal : `"${userRefOrVal}"`;
  const passExpr = passRefOrVal.startsWith('"') || passRefOrVal.match(/^[A-Z]+\d+$/) ? passRefOrVal : `"${passRefOrVal}"`;
  const mobileExpr = mobileCellRef.match(/^[A-Z]+\d+$/) ? mobileCellRef : `"${mobileCellRef}"`;
  const nameExpr = nameCellRef.match(/^[A-Z]+\d+$/) ? nameCellRef : `"${nameCellRef}"`;
  const msgExpr = messageCellRefOrText.match(/^[A-Z]+\d+$/) ? messageCellRefOrText : `"${messageCellRefOrText.replace(/"/g, '""')}"`;

  return `=HYPERLINK("https://app.messageautosender.com/message/new?username="&${userExpr}&"&password="&${passExpr}&"&receiverMobileNo="&${mobileExpr}&"&receiverName="&${nameExpr}&"&message="&${msgExpr}, "${label}")`;
}

/**
 * Construct standard WhatsApp wa.me / api.whatsapp.com URL
 */
export function buildStandardWhatsAppUrl(receiverMobileNo: string, message: string): string {
  const cleanMobile = formatPhoneNumber(receiverMobileNo);
  const encodedMsg = encodeURIComponent(message || '');
  return `https://wa.me/${cleanMobile}?text=${encodedMsg}`;
}

/**
 * Construct mailto: URL for default email client
 */
export function buildMailtoUrl(toEmail: string, subject: string, body: string): string {
  const encodedSub = encodeURIComponent(subject || '');
  const encodedBody = encodeURIComponent(body || '');
  return `mailto:${toEmail}?subject=${encodedSub}&body=${encodedBody}`;
}

/**
 * Triggers sending WhatsApp message via app.messageautosender.com or opens WhatsApp Web
 */
export async function sendWhatsAppNotification(params: {
  username?: string;
  password?: string;
  receiverMobileNo: string;
  receiverName: string;
  message: string;
  preferDirectApi?: boolean;
}): Promise<{ success: boolean; method: 'api' | 'web' | 'formula_copied'; message: string; url: string }> {
  const { username = '', password = '', receiverMobileNo, receiverName, message, preferDirectApi = true } = params;
  const cleanMobile = formatPhoneNumber(receiverMobileNo);

  if (!cleanMobile) {
    return {
      success: false,
      method: 'web',
      message: 'Mobile number is missing or invalid.',
      url: ''
    };
  }

  // If username and password are provided for MessageAutoSender
  if (username && password && preferDirectApi) {
    const autoSenderUrl = buildMessageAutoSenderUrl(username, password, cleanMobile, receiverName, message);
    
    // Attempt fetch call to trigger MessageAutoSender API endpoint
    try {
      const resp = await fetch(autoSenderUrl, { mode: 'no-cors' });
      // Opening in popup / new tab as well to ensure delivery if browser CORS blocks response
      window.open(autoSenderUrl, '_blank', 'noopener,noreferrer');
      return {
        success: true,
        method: 'api',
        message: `WhatsApp message dispatched via MessageAutoSender for ${receiverName} (${cleanMobile})`,
        url: autoSenderUrl
      };
    } catch (err) {
      // Fallback to opening window
      window.open(autoSenderUrl, '_blank', 'noopener,noreferrer');
      return {
        success: true,
        method: 'api',
        message: `Opened MessageAutoSender portal for ${receiverName}`,
        url: autoSenderUrl
      };
    }
  } else {
    // Fallback to standard WhatsApp Web wa.me link
    const waUrl = buildStandardWhatsAppUrl(cleanMobile, message);
    window.open(waUrl, '_blank', 'noopener,noreferrer');
    return {
      success: true,
      method: 'web',
      message: `Opened WhatsApp chat for ${receiverName}`,
      url: waUrl
    };
  }
}
